### ISSUE TITLE
how you calculated the final F1 score recorded in the paper

### ISSUE THREAD

**Issue by techzzt** [andrewlai61616/NPSR#1]
Hello, I find your research intriguing and have been experimenting with the code. 

I was able to observe various F1 scores for each batch. 
I'm curious about how you obtained the overall results for the entire dataset as mentioned in the paper. 
Should I check the final results displayed in the experiment output to get that information?

**Comment by andrewlai61616** [comment]
Yes, the final results were parsed and extracted from the output file.

Please refer to Appendix C in our paper for implementation details.

**Comment by techzzt** [comment]
Thank you so much for your response. The information you provided has been very helpful!
