### ISSUE TITLE
Meet Problems with processing the WADI dataset

### ISSUE THREAD

**Issue by DavidDong004** [andrewlai61616/NPSR#2]
Thank you very much for sharing such a good model with us. I'm now trying to reproduce your model, but I meet a problem with the WADI dataset: 
While putting the 2017 version of the data WADI_14days.csv and WADI_attackdata.csv into datasets and processing them with make_pk.py, on line 17 " assert len(set(lab_tst)) == 2" there is an error.
 I tried to print the value and its value is 99. How can I solve this problem please?

**Comment by andrewlai61616** [comment]
Hi,

Thank you for pointing this out.
Please copy the values for the label column (Attack LABLE (1: No Attack, -1: Attack)) in the 2019 dataset and paste it to the last column of the 2017 version.

**Comment by DavidDong004** [comment]
Thank ypu so much,that helps a lot.
