### ISSUE TITLE
lab_tst标签的选择

### ISSUE THREAD

**Issue by Shawn86CN** [andrewlai61616/NPSR#4]
您代码中NPSR-main/utils/process(15) downsample_data函数中对于lab_tst的处理
reduce_func = np.min if all_should_be_anomaly else np.max，
这样处理是否会忽略掉较多的分布零散的异常数据

In the downsample_data function for lab_tst in NPSR-main/utils/process(15), where 
reduce_func = np.min if all_should_be_anomaly else np.max, 
does this processing ignore a significant amount of sparsely distributed anomaly data?

**Comment by andrewlai61616** [comment]
I think this will depend on the dataset. This section of code corresponds to a dataset with only 0's and 1's, as in the if statement [(arr == 0).sum() + (arr == 1).sum() == np.prod(arr.shape)].

**Comment by Shawn86CN** [comment]
Okay, I understand. Thank you for your reply.
